"use client";
import {useEffect,useRef,useState} from "react";
import LandmarkReels from "../../lib/LandmarkReels";
import PersonSilhouette from "../../lib/PersonSilhouette";
import {supabase} from "../../lib/supabase";
import {PIN,people,clues,progress} from "../../lib/game";
type Room={id:string;pin:string;phase:string;current_question:number};
type Player={id:string;display_name:string;score?:number};
export default function Play(){
 const[pin,setPin]=useState(""),[name,setName]=useState(""),[room,setRoom]=useState<Room|null>(null),[player,setPlayer]=useState<Player|null>(null),[winner,setWinner]=useState<Player|null>(null),[choice,setChoice]=useState<number|null>(null),[sent,setSent]=useState(false),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);const start=useRef(Date.now());
 useEffect(()=>{const x=new URLSearchParams(location.search).get("pin");if(x)setPin(x);const stored=localStorage.getItem("three-kind-player");if(!stored)return;try{const ids=JSON.parse(stored);Promise.all([supabase.from("rooms").select("*").eq("id",ids.room).single(),supabase.from("players").select("*").eq("id",ids.player).single()]).then(([r,p])=>{if(r.data&&p.data&&p.data.room_id===r.data.id){setRoom(r.data as Room);setPlayer(p.data as Player);setName(p.data.display_name)}else localStorage.removeItem("three-kind-player")})}catch{localStorage.removeItem("three-kind-player")}},[]);
 useEffect(()=>{if(room?.phase!=="final")return;supabase.from("players").select("*").eq("room_id",room.id).then(({data})=>{const top=(data||[]).sort((a,b)=>(b.score||0)-(a.score||0)||(a.total_correct_ms||0)-(b.total_correct_ms||0)||a.display_name.localeCompare(b.display_name)||a.id.localeCompare(b.id))[0];setWinner(top||null)})},[room?.id,room?.phase]);
 useEffect(()=>{if(!room||!player)return;let active=true;async function sync(){const[{data:r},{data:p}]=await Promise.all([supabase.from("rooms").select("*").eq("id",room!.id).single(),supabase.from("players").select("*").eq("id",player!.id).single()]);if(!active)return;if(r){setRoom(prev=>{if(prev?.current_question!==r.current_question||prev?.phase!==r.phase)start.current=Date.now();return r as Room})}if(p)setPlayer(p as Player);if(r?.phase==="voting"){const{data:v}=await supabase.from("votes").select("choice").eq("room_id",room!.id).eq("player_id",player!.id).eq("question",r.current_question).maybeSingle();if(active){setSent(!!v);setChoice(v?.choice??null)}}}sync();const timer=setInterval(sync,1000);return()=>{active=false;clearInterval(timer)}},[room?.id,player?.id]);

 async function join(){if(pin.trim().toUpperCase()!==PIN){setMsg("Check the course PIN and try again.");return}setBusy(true);setMsg("");const{data:r,error:roomError}=await supabase.from("rooms").select("*").ilike("pin",PIN).single();if(!r){setMsg(roomError?.message||"Room not open yet.");setBusy(false);return}const{data:p,error}=await supabase.from("players").insert({room_id:r.id,display_name:name.trim()}).select().single();if(error||!p){setMsg(error?.message||"Could not join.");setBusy(false);return}localStorage.setItem("three-kind-player",JSON.stringify({room:r.id,player:p.id}));setRoom(r as Room);setPlayer(p as Player);setBusy(false)}
 async function submit(){if(choice===null||sent||busy||room?.phase!=="voting"||!player)return;setBusy(true);setMsg("");const{error}=await supabase.from("votes").insert({room_id:room.id,player_id:player.id,question:room.current_question,choice,response_ms:Date.now()-start.current});if(!error)setSent(true);else setMsg(error.message);setBusy(false)}
 if(!player)return <main className="player"><header><div><span className="eyebrow"><span className="course">EdD Org Leadership · Collaborative Learning · LEAD-697-01</span><a className="assignment" href="https://sandiego.instructure.com/courses/32844/assignments/453024" target="_blank" rel="noreferrer">♠ Assignment: Triad Get-to-Know-You Introductions ♦</a></span><h1>🎰 THREE OF A KIND</h1></div><div className="header-right"><div className="team"><b>♣ TEAM MEMBERS ♥</b><span>LaShea Conner-Gaten</span><span>Benjamin Frandsen</span><span>Joshua Lewis</span></div></div></header><section className="machine"><div className="reel"><div><h2>Join the game</h2><label>Course PIN<input autoCapitalize="off" placeholder="SOLES#3" value={pin} onChange={e=>setPin(e.target.value)}/></label><label>Your real first and last name — we’ll announce the winner<input maxLength={60} autoComplete="name" placeholder="First and last name" value={name} onChange={e=>setName(e.target.value)}/></label></div></div><div className="actions"><button className="spin" disabled={busy||!pin.trim()||!name.trim()} onClick={join}>JOIN GAME</button></div><p role="alert" className="notice">{msg}</p></section></main>;
 const q=room?.current_question||0,phase=room?.phase||"lobby",shown=progress(q,phase);return <main className="player"><header><div><span className="eyebrow"><span className="course">EdD Org Leadership · Collaborative Learning · LEAD-697-01</span><a className="assignment" href="https://sandiego.instructure.com/courses/32844/assignments/453024" target="_blank" rel="noreferrer">♠ Assignment: Triad Get-to-Know-You Introductions ♦</a> • {player.display_name}</span><h1>🎰 THREE OF A KIND</h1></div><div className="header-right"><div className="team"><b>♣ TEAM MEMBERS ♥</b><span>LaShea Conner-Gaten</span><span>Benjamin Frandsen</span><span>Joshua Lewis</span></div><div className="score">QUESTION <b>{q+1}/6</b></div></div></header><section className="mysteries">{people.map((p,i)=><div className="person" key={p}><PersonSilhouette index={i} shown={shown[i]}/><b>{p}</b><small>{shown[i]}/2 clues</small></div>)}</section><section className="machine">
 {phase==="lobby"&&<div className="reel"><h2>✓ You’re in! Watch the shared screen.</h2></div>}
 {phase==="voting"&&<><div className="reel"><div><LandmarkReels round={q}/><span className="reel-icon">{clues[q].icon}</span><h2>{clues[q].text}</h2></div></div><p className="prompt">{sent?"🔒 ANSWER LOCKED":"WHO DAT?!"}</p><div className="choices">{people.map((p,i)=><button key={p} disabled={sent} className={choice===i?"selected":""} onClick={()=>setChoice(i)}>{p}</button>)}</div>{!sent&&<div className="actions"><button className="spin" disabled={choice===null||busy} onClick={submit}>LOCK IN</button></div>}</>}
 {phase==="results"&&<div className="reel"><div><LandmarkReels spinning round={q}/><h2>Votes are in. Watch the host spin to reveal! 🎰</h2></div></div>}
 {phase==="reveal"&&<div className="reveal"><LandmarkReels revealOwner={clues[q].owner} round={q}/><span>THE CLUE BELONGS TO…</span><h2>{people[clues[q].owner]}!</h2><p>{choice===clues[q].owner?"✓ You got it!":"Next clue coming up…"}</p><div className="story-card"><b>THE STORY</b><p>{clues[q].story}</p></div></div>}
 {phase==="final"&&<div className="reveal"><div className="confetti" aria-hidden="true">🎉 ✨ 🎊 ✨ 🎉</div><span>JACKPOT CHAMPION</span><h2 className="winner-name">🏆 {winner?.display_name||"Winner loading…"}</h2><p>{winner?`${winner.score||0}/6 correct · ${winner.id===player.id?"That’s you! Your $25 virtual Visa card will be sent today to your USD student email.":"Thanks for playing! #SOLESCohort3 #BoldBalancedBecoming"}`:"Check the shared screen for the winner."}</p></div>}
 {msg&&<p className="notice" role="alert">{msg}</p>}</section></main>
}
