"use client";
import {useEffect,useRef,useState} from "react";
import {ROUND_SECONDS,readerFor} from "../lib/game";
import LandmarkReels from "../lib/LandmarkReels";
import PersonSilhouette from "../lib/PersonSilhouette";
import PotOfGold from "../lib/PotOfGold";
import HowToPlay from "../lib/HowToPlay";
import BackstoryTimer from "../lib/BackstoryTimer";
import {miss} from "../lib/sfx";
import {VictoryFanfare} from "../lib/SoundFx";
const people=["LaShea C.G.","Benjamin F.","Joshua L."];
const clues=[
{owner:0,text:"I once won a pig-calling contest at the State Fair.",icon:"🐷",story:"Joshua will share how LaShea won a pig-calling contest at the State Fair."},
{owner:2,text:"I used to avidly collect Yu-Gi-Oh! and Pokémon cards.",icon:"🃏",story:"Benjamin will share the story behind Joshua’s Yu-Gi-Oh! and Pokémon card collection."},
{owner:1,text:"My first-ever LinkedIn post had over 1 million views.",icon:"📈",story:"LaShea will share the story behind Benjamin’s first-ever LinkedIn post hitting over 1 million views."},
{owner:0,text:"I helped deliver a baby in a car.",icon:"👶🏾",story:"Joshua will share how LaShea helped deliver a baby in a car."},
{owner:1,text:"I’ve earned 9 associate degrees.",icon:"🎓",story:"LaShea will share how Benjamin earned 9 associate degrees."},
{owner:2,text:"As a kid, I played for Team USA on an under-12 basketball team at a tournament in Australia.",icon:"🏀",story:"Benjamin will share how Joshua played for Team USA in Australia before he turned 12."}
];
export default function Home(){
const[started,setStarted]=useState(false);const[q,setQ]=useState(0);const[vote,setVote]=useState<number|null>(null);const[locked,setLocked]=useState(false);const[revealed,setRevealed]=useState(false);const[score,setScore]=useState(0);const[spinning,setSpinning]=useState(false);const spinTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const[clock,setClock]=useState(ROUND_SECONDS);const[timeUp,setTimeUp]=useState(false);
const c=clues[q];const seen=clues.slice(0,q+(revealed?1:0));const progress=people.map((_,i)=>seen.filter(x=>x.owner===i).length);
useEffect(()=>{if(!started||locked||revealed||spinning)return;const deadline=Date.now()+clock*1000;const t=setInterval(()=>{const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));setClock(left);if(left<=0){clearInterval(t);setTimeUp(true);setLocked(true)}},200);return()=>clearInterval(t)},[started,q,locked,revealed,spinning]);
function spin(){if(spinning||revealed)return;if(vote===null&&!timeUp)return;setLocked(true);setSpinning(true);if(spinTimer.current)clearTimeout(spinTimer.current);spinTimer.current=setTimeout(()=>{setSpinning(false);if(vote===c.owner)setScore(v=>v+1);else setTimeout(miss,500);setRevealed(true)},2200)}
function restart(){if(spinTimer.current)clearTimeout(spinTimer.current);setStarted(false);setQ(0);setVote(null);setLocked(false);setRevealed(false);setScore(0);setSpinning(false);setClock(ROUND_SECONDS);setTimeUp(false);}
function next(){if(q<5){setQ(x=>x+1);setVote(null);setLocked(false);setRevealed(false);setClock(ROUND_SECONDS);setTimeUp(false);}}
return <main>
<header><div className="header-meta"><span className="course">EdD Org Leadership · Collaborative Learning · LEAD-697-01</span><span className="date-badge">📅 Wednesday, September 30th</span></div><div className="header-brand"><span className="eyebrow"><a className="assignment" href="https://sandiego.instructure.com/courses/32844/assignments/453024" target="_blank" rel="noreferrer">Assignment · Triad Get-to-Know-You Introductions</a></span><h1 className="brand-title"><span className="title-suit" aria-hidden="true">♠</span><span className="title-text">THREE OF A KIND</span><span className="title-suit" aria-hidden="true">♦</span></h1><p className="tagline"><span>6 clues</span><i>✦</i><span>3 people</span><i>✦</i><span className="luck">Test your luck 🍀</span></p></div><div className="header-right"><div className="team"><b>Team Members</b><span>LaShea Conner-Gaten</span><span>Benjamin Frandsen</span><span>Joshua Lewis</span></div><div className="score-row"><PotOfGold count={score}/><div className="score">SCORE <b>{score}/6</b></div></div></div></header><HowToPlay mode="solo"/>
<nav className="host-tools"><a href="/host">LIVE HOST DASHBOARD</a><a href="/play">JOIN LIVE CLASS GAME</a><button className="live-restart" onClick={restart}>RESTART SOLO GAME</button></nav>
{!started?<section className="machine"><div className="reel"><div><h2>Ready for a fresh game?</h2><p>Six clues. The timer starts when you press Start.</p><button className="spin" onClick={()=>setStarted(true)}>START SOLO GAME</button><p>For shared class percentages, open the Live Host Dashboard.</p></div></div></section>:<><section className="mysteries">{people.map((p,i)=><div className={"person "+(progress[i]===3?"complete":"")} key={p}><PersonSilhouette index={i} shown={progress[i]}/><b>{p}</b><small>{progress[i]}/2 clues discovered</small></div>)}</section>
<section className="machine"><div className="question">QUESTION {q+1} OF 6</div><div className="reel"><div className="slot-content">{!spinning&&!revealed?<><LandmarkReels round={q}/><div className="clue-ticket" aria-live="polite"><span className="clue-ticket-label">CLUE {q+1}</span><div className="icon">{c.icon}</div><h2>{c.text}</h2></div></>:<><LandmarkReels spinning={spinning} revealOwner={revealed?c.owner:undefined} round={q} action={revealed?(q<5?<button className="spin next-in-machine" onClick={next}>NEXT CLUE ➜</button>:<span className="final-in-machine">🏆 FINAL SCORE: {score}/6<VictoryFanfare/></span>):undefined}/>{spinning&&<p className="spin-callout">LEVER PULLED — REVEALING…</p>}</>}</div></div>{!revealed&&!spinning?<><p className="prompt">{timeUp&&vote===null?"⏰ TIME’S UP! · PULL THE LEVER TO SEE WHO":locked?"🔒 ANSWER LOCKED":"WHO DAT?!"}</p>{!locked&&<div className={`timer ${clock<=5?"is-urgent":""}`}><b aria-live="polite">{clock}s</b><div className="countdown"><span style={{width:`${clock*100/ROUND_SECONDS}%`}}/></div></div>}<div className="choices">{people.map((p,i)=><button disabled={locked} className={vote===i?"selected":""} onClick={()=>setVote(i)} key={p}>{p}</button>)}</div><div className="actions"><button className="spin pull-lever" disabled={vote===null&&!timeUp} onClick={spin}>🎰 LOCK IN &amp; PULL THE LEVER</button></div></>:revealed?<div className="reveal"><span>THE CLUE BELONGS TO…</span><h2>{people[c.owner]}!</h2><p>{vote===c.owner?"✓ Correct! +1 point":"Keep detecting!"}</p><div className="story-card"><b>THE BACKSTORY</b><BackstoryTimer key={q}/><p className="teller">🎤 Told by {readerFor(c.owner)}</p><p>{c.story}</p></div></div>:null}
</section></>}<footer>Three people • Six clues • One winner · <a href="https://www.sandiego.edu/facilities/building-gallery.php" target="_blank" rel="noreferrer">USD campus photos</a></footer></main>}