"use client";
import {useEffect,useRef,useState} from "react";
import {ROUND_SECONDS} from "../lib/game";
import LandmarkReels from "../lib/LandmarkReels";
import PersonSilhouette from "../lib/PersonSilhouette";
import PotOfGold from "../lib/PotOfGold";
const people=["LaShea C.G.","Benjamin F.","Joshua L."];
const clues=[
{owner:0,text:"I once won a pig-calling contest at the State Fair.",icon:"🐷",story:"Backstory coming soon — LaShea will share how the pig-calling contest happened."},
{owner:2,text:"Mystery clue from Joshua.",icon:"✨",story:"Backstory coming soon from Joshua."},
{owner:1,text:"My first-ever LinkedIn post had over 1 million views.",icon:"📈",story:"Backstory coming soon from Benjamin."},
{owner:0,text:"I helped deliver a baby in a car.",icon:"👶🏾",story:"Backstory coming soon — LaShea will share the car-delivery story."},
{owner:1,text:"Second mystery clue from Benjamin.",icon:"🎲",story:"Second backstory coming soon from Benjamin."},
{owner:2,text:"Second mystery clue from Joshua.",icon:"💫",story:"Second backstory coming soon from Joshua."}
];
export default function Home(){
const[q,setQ]=useState(0);const[vote,setVote]=useState<number|null>(null);const[locked,setLocked]=useState(false);const[revealed,setRevealed]=useState(false);const[score,setScore]=useState(0);const[spinning,setSpinning]=useState(false);const spinTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const[clock,setClock]=useState(ROUND_SECONDS);const[timeUp,setTimeUp]=useState(false);
const c=clues[q];const seen=clues.slice(0,q+(revealed?1:0));const progress=people.map((_,i)=>seen.filter(x=>x.owner===i).length);
useEffect(()=>{if(locked||revealed||spinning)return;const deadline=Date.now()+clock*1000;const t=setInterval(()=>{const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));setClock(left);if(left<=0){clearInterval(t);setTimeUp(true);setLocked(true)}},200);return()=>clearInterval(t)},[q,locked,revealed,spinning]);
function spin(){if(spinning||!locked)return;setSpinning(true);if(spinTimer.current)clearTimeout(spinTimer.current);spinTimer.current=setTimeout(()=>{setSpinning(false);if(vote===c.owner)setScore(v=>v+1);setRevealed(true)},2200)}
function reveal(){if(vote===null)return;if(!locked){setLocked(true);return}spin()}
function next(){if(q<5){setQ(x=>x+1);setVote(null);setLocked(false);setRevealed(false);setClock(ROUND_SECONDS);setTimeUp(false);}}
return <main>
<header><div className="header-meta"><span className="course">EdD Org Leadership · Collaborative Learning · LEAD-697-01</span><span className="date-badge">📅 Wednesday, September 30th</span></div><div className="header-brand"><span className="eyebrow"><a className="assignment" href="https://sandiego.instructure.com/courses/32844/assignments/453024" target="_blank" rel="noreferrer">Assignment · Triad Get-to-Know-You Introductions</a></span><h1 className="brand-title"><span className="title-suit" aria-hidden="true">♠</span><span className="title-text">THREE OF A KIND</span><span className="title-suit" aria-hidden="true">♦</span></h1><p className="tagline"><span>6 clues</span><i>✦</i><span>3 people</span><i>✦</i><span className="luck">Test your luck 🍀</span></p></div><div className="header-right"><div className="team"><b>Team Members</b><span>LaShea Conner-Gaten</span><span>Benjamin Frandsen</span><span>Joshua Lewis</span></div><div className="score-row"><PotOfGold count={score}/><div className="score">SCORE <b>{score}/6</b></div></div></div></header>
<section className="mysteries">{people.map((p,i)=><div className={"person "+(progress[i]===3?"complete":"")} key={p}><PersonSilhouette index={i} shown={progress[i]}/><b>{p}</b><small>{progress[i]}/2 clues discovered</small></div>)}</section>
<section className="machine"><div className="question">QUESTION {q+1} OF 6</div><div className="reel"><div className="slot-content">{!spinning&&!revealed?<><LandmarkReels round={q}/><div className="clue-ticket" aria-live="polite"><span className="clue-ticket-label">CLUE {q+1}</span><div className="icon">{c.icon}</div><h2>{c.text}</h2></div></>:<><LandmarkReels spinning={spinning} revealOwner={revealed?c.owner:undefined} round={q}/>{spinning&&<p className="spin-callout">LEVER PULLED — REVEALING…</p>}</>}</div></div>{!revealed&&!spinning?<><p className="prompt">{timeUp&&vote===null?"⏰ TIME’S UP! · PULL THE LEVER TO SEE WHO":locked?"🔒 ANSWER LOCKED · READY TO PULL THE LEVER":"WHO DAT?!"}</p>{!locked&&<div className={`timer ${clock<=5?"is-urgent":""}`}><b aria-live="polite">{clock}s</b><div className="countdown"><span style={{width:`${clock*100/ROUND_SECONDS}%`}}/></div></div>}<div className="choices">{people.map((p,i)=><button disabled={locked} className={vote===i?"selected":""} onClick={()=>setVote(i)} key={p}>{p}</button>)}</div><div className="actions"><button className="spin pull-lever" disabled={vote===null&&!timeUp} onClick={locked?spin:reveal}>{locked?"PULL THE LEVER ⬇":"LOCK IN"}</button></div></>:revealed?<div className="reveal"><span>THE CLUE BELONGS TO…</span><h2>{people[c.owner]}!</h2><p>{vote===c.owner?"✓ Correct! +1 point":"Keep detecting!"}</p>{q<5?<button className="spin" onClick={next}>NEXT CLUE ↻</button>:<div className="final">FINAL SCORE: <b>{score}/6</b></div>}</div>:null}
</section><footer>Three people • Six clues • One winner · <a href="https://www.sandiego.edu/facilities/building-gallery.php" target="_blank" rel="noreferrer">USD campus photos</a></footer></main>}