"use client";
import {useCallback,useEffect,useState} from "react";
import {QRCodeSVG} from "qrcode.react";
import LandmarkReels from "../../lib/LandmarkReels";
import {supabase} from "../../lib/supabase";
import {PIN,people,clues,progress,ROUND_SECONDS} from "../../lib/game";

type Room={id:string;pin:string;phase:string;current_question:number;updated_at?:string};
type Player={id:string;display_name:string;score:number;total_correct_ms:number};
type Vote={id:string;question:number;choice:number};
export default function Host(){
 const[authed,setAuthed]=useState(false);const[authMessage,setAuthMessage]=useState("");const[room,setRoom]=useState<Room|null>(null),[players,setPlayers]=useState<Player[]>([]),[votes,setVotes]=useState<Vote[]>([]),[url,setUrl]=useState(""),[clock,setClock]=useState(ROUND_SECONDS),[spinning,setSpinning]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user?.email?.toLowerCase()==="lconnergaten@caicollectivegroup.com")setAuthed(true)});const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>setAuthed(session?.user?.email?.toLowerCase()==="lconnergaten@caicollectivegroup.com"));return()=>listener.subscription.unsubscribe()},[]);
 useEffect(()=>{setUrl(`${location.origin}/play?pin=${encodeURIComponent(PIN)}`);const id=sessionStorage.getItem("three-kind-host");if(id)supabase.from("rooms").select("*").eq("id",id).single().then(({data})=>{if(data)setRoom(data as Room);else sessionStorage.removeItem("three-kind-host")})},[]);
 const refresh=useCallback(async()=>{if(!room)return;const[{data:r},{data:p},{data:v}]=await Promise.all([supabase.from("rooms").select("*").eq("id",room.id).single(),supabase.from("players").select("*").eq("room_id",room.id),supabase.from("votes").select("*").eq("room_id",room.id)]);if(r)setRoom(r as Room);setPlayers((p||[]) as Player[]);setVotes((v||[]) as Vote[])},[room?.id]);
 useEffect(()=>{if(!room)return;refresh();const timer=setInterval(refresh,1000);return()=>clearInterval(timer)},[room?.id,refresh]);
 useEffect(()=>{if(room?.phase!=="voting")return;setClock(ROUND_SECONDS);const timer=setInterval(()=>setClock(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[room?.current_question,room?.phase]);
 async function sendHostLink(){setAuthMessage("");const {error}=await supabase.auth.signInWithOtp({email:"lconnergaten@caicollectivegroup.com",options:{emailRedirectTo:`${location.origin}/host`,shouldCreateUser:true}});setAuthMessage(error?.message||"Check your CAI email for the sign-in link, then return to this screen.")}
 async function create(){setBusy(true);setMessage("");const{data:existing}=await supabase.from("rooms").select("*").ilike("pin",PIN).maybeSingle();if(existing){setRoom(existing as Room);sessionStorage.setItem("three-kind-host",existing.id);setMessage("Resumed the room using this course PIN.");setBusy(false);return}const{data,error}=await supabase.from("rooms").insert({pin:PIN}).select().single();if(data){setRoom(data as Room);sessionStorage.setItem("three-kind-host",data.id)}else setMessage(error?.message||"Could not create the room. Check the database setup.");setBusy(false)}
 async function setPhase(phase:string,next=false){if(!room||busy)return;setBusy(true);setMessage("");if(phase==="final"){const{error}=await supabase.rpc("finalize_game_scores",{target_room:room.id});if(error){setMessage(`Could not score the game: ${error.message}`);setBusy(false);return}await refresh()}
 const q=next?Math.min(room.current_question+1,8):room.current_question;const{data,error}=await supabase.from("rooms").update({phase,current_question:q}).eq("id",room.id).select().single();if(data)setRoom(data as Room);else setMessage(error?.message||"Could not advance the game.");setBusy(false)}
 function spinNext(first=false){if(spinning||busy)return;setSpinning(true);setTimeout(async()=>{await setPhase("voting",!first);setSpinning(false)},1800)}
 const q=room?.current_question||0,phase=room?.phase||"lobby",qv=votes.filter(v=>v.question===q),counts=people.map((_,i)=>qv.filter(v=>v.choice===i).length),revealed=progress(q,phase);
 if(!authed)return <main className="host"><header><h1>🎰 THREE OF A KIND</h1></header><section className="machine"><div className="reel"><div><h2>Host sign-in</h2><p>The host link will be emailed to LaShea’s CAI address.</p></div></div><div className="actions"><button className="spin" onClick={sendHostLink}>EMAIL HOST LINK</button></div><p role="status" className="notice">{authMessage}</p></section></main>;
 return <main className="host"><header><div><span className="eyebrow">SOLES • ALCALÁ PARK • PIN {PIN}</span><h1>🎰 THREE OF A KIND</h1><p>9 clues. 3 people. How well can you read the room?</p></div><div className="score">QUESTION <b>{room?`${q+1}/9`:"READY"}</b></div></header>
 {room&&<section className="mysteries">{people.map((p,i)=><div className="person" key={p}><div className="silhouette" aria-label={`${revealed[i]} of 3 clues shown`}><div className="silhouette-fill" style={{height:`${revealed[i]*100/3}%`}}>◆</div><div className="silhouette-outline">◆</div></div><b>{p}</b><small>{revealed[i]}/3 clues</small></div>)}</section>}
 <section className="machine"><div className="question">{room?phase.toUpperCase():"GET READY"}</div>
 {!room&&<><div className="reel"><h2>Open the live room</h2></div><div className="actions"><button className="spin" disabled={busy} onClick={create}>CREATE LIVE ROOM</button></div></>}
 {room&&phase==="lobby"&&!spinning&&<><div className="reel join-reel"><div><h2>SCAN TO JOIN</h2>{url&&<div className="qr"><QRCodeSVG value={url} size={175} includeMargin/></div>}<p><a href={url}>{url}</a></p><div className="pinCard">Course PIN <b>{PIN}</b></div><p>{players.length} players connected · Android and iPhone browsers welcome</p></div></div><div className="actions"><button className="spin" disabled={busy} onClick={()=>spinNext(true)}>START & SPIN</button></div></>}
 {room&&spinning&&<div className="reel slot-reel"><div className="slot-content"><LandmarkReels spinning/><p className="spin-callout" aria-live="polite">REELS SPINNING…</p></div></div>}
 {room&&phase==="voting"&&!spinning&&<><div className={`reel slot-reel ${spinning?"is-spinning":""}`}><div><LandmarkReels spinning={spinning}/><span className="reel-icon">{clues[q].icon}</span><h2>{clues[q].text}</h2></div></div><p className="prompt">WHO DAT?! · {qv.length} / {players.length} answers · <span aria-live="polite">{clock}s</span></p><div className="countdown"><span style={{width:`${clock*100/ROUND_SECONDS}%`}}/></div><div className="actions"><button className="spin" disabled={busy} onClick={()=>setPhase("results")}>LOCK VOTING</button></div></>}
 {room&&phase==="results"&&<><div className="reel"><div className="results"><h2>ROOM TALLY</h2>{people.map((p,i)=><div className="result" key={p}><div><b>{p}</b><b>{Math.round(counts[i]/(qv.length||1)*100)}%</b></div><div className="result-track"><span style={{width:`${counts[i]/(qv.length||1)*100}%`}}/></div></div>)}</div></div><div className="actions"><button className="spin" disabled={busy} onClick={()=>setPhase("reveal")}>REVEAL ANSWER ✨</button></div></>}
 {room&&phase==="reveal"&&!spinning&&<div className="reveal"><span>THE CLUE BELONGS TO…</span><h2>{people[clues[q].owner]}!</h2><p>🎤 Pause for the story behind the clue.</p>{q<8?<button className="spin" disabled={busy||spinning} onClick={()=>spinNext()}>{spinning?"SPINNING…":"NEXT SPIN 🎰"}</button>:<button className="spin" disabled={busy} onClick={()=>setPhase("final")}>FINAL JACKPOT 🏆</button>}</div>}
 {room&&phase==="final"&&<div className="reveal"><span>FINAL JACKPOT</span><h2>🏆 TOP 3 DETECTIVES</h2>{[...players].sort((a,b)=>(b.score||0)-(a.score||0)||(a.total_correct_ms||0)-(b.total_correct_ms||0)).slice(0,3).map((p,i)=><p key={p.id} className="podium">{["🥇","🥈","🥉"][i]} {p.display_name} — {p.score||0}/9</p>)}</div>}
 {message&&<p role="alert" className="notice">{message}</p>}</section><footer>Three people • Nine clues • Nine minutes</footer></main>
}
